"""
Integration Tests - FASE 7 GitHub Integration
Valida: GitHub API integration, workflow orchestration
"""
import asyncio
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from app.services.github_service import GitHubIntegration, GitHubWorkflow
import structlog

logger = structlog.get_logger(__name__)


class GitHubTester:
    """Integration test suite for FASE 7"""

    def __init__(self):
        self.passed = 0
        self.failed = 0
        self.tests_result = []

    async def test_github_service_init(self):
        """Test 1: GitHubIntegration initializes correctly"""
        try:
            service = GitHubIntegration("test_token_dummy")
            assert service.access_token == "test_token_dummy"
            assert service.api_url == "https://api.github.com"
            assert "Authorization" in service.headers
            self._log_pass("Test 1: GitHubIntegration initializes")

        except Exception as e:
            self._log_fail(f"Test 1: {str(e)}")

    async def test_github_workflow_init(self):
        """Test 2: GitHubWorkflow initializes correctly"""
        try:
            workflow = GitHubWorkflow("test_token_dummy")
            assert workflow.github is not None
            assert isinstance(workflow.github, GitHubIntegration)
            self._log_pass("Test 2: GitHubWorkflow initializes")

        except Exception as e:
            self._log_fail(f"Test 2: {str(e)}")

    async def test_headers_construction(self):
        """Test 3: GitHub headers are constructed correctly"""
        try:
            token = "ghp_test_1234567890abcdef"
            service = GitHubIntegration(token)

            assert service.headers["Authorization"] == f"token {token}"
            assert service.headers["Accept"] == "application/vnd.github.v3+json"
            assert service.headers["Content-Type"] == "application/json"

            self._log_pass("Test 3: GitHub headers constructed correctly")

        except Exception as e:
            self._log_fail(f"Test 3: {str(e)}")

    async def test_branch_name_generation(self):
        """Test 4: Branch name generation"""
        try:
            from datetime import datetime, timezone

            project_name = "test-project"
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            branch_name = f"gca/generated-{project_name}-{timestamp}"

            # Verify format
            assert branch_name.startswith("gca/generated-")
            assert project_name in branch_name
            assert len(branch_name) > 0

            self._log_pass(f"Test 4: Branch name generation (format: gca/generated-*)")

        except Exception as e:
            self._log_fail(f"Test 4: {str(e)}")

    async def test_commit_message_construction(self):
        """Test 5: Commit message construction"""
        try:
            project_name = "ecommerce-platform"
            commit_message = f"GCA: Generated code for {project_name}"

            assert "GCA:" in commit_message
            assert project_name in commit_message
            assert len(commit_message) > 0

            self._log_pass("Test 5: Commit message constructed correctly")

        except Exception as e:
            self._log_fail(f"Test 5: {str(e)}")

    async def test_pr_body_construction(self):
        """Test 6: Pull request body construction"""
        try:
            project_name = "web-app"
            file_path = "generated/code.py"
            branch_name = "gca/generated-web-app-20260405"

            pr_body = f"""# Generated Code: {project_name}

Generated by GCA (Gestão de Codificação Assistida)

## Changes
- Generated code file: `{file_path}`
- Branch: `{branch_name}`

## Ready for review
Please review the generated code and merge if approved."""

            assert project_name in pr_body
            assert file_path in pr_body
            assert "GCA" in pr_body
            assert len(pr_body) > 50

            self._log_pass("Test 6: PR body constructed correctly")

        except Exception as e:
            self._log_fail(f"Test 6: {str(e)}")

    async def test_api_url_construction(self):
        """Test 7: GitHub API URL construction"""
        try:
            base_url = "https://api.github.com"
            owner = "pielak"
            repo = "gca"

            # Test various endpoint URLs
            user_url = f"{base_url}/user"
            repos_url = f"{base_url}/user/repos"
            branches_url = f"{base_url}/repos/{owner}/{repo}/git/refs/heads/main"
            prs_url = f"{base_url}/repos/{owner}/{repo}/pulls"

            assert user_url.startswith("https://api.github.com")
            assert repos_url.startswith("https://api.github.com")
            assert branches_url.startswith("https://api.github.com")
            assert prs_url.startswith("https://api.github.com")
            assert owner in branches_url
            assert repo in branches_url

            self._log_pass("Test 7: GitHub API URLs constructed correctly")

        except Exception as e:
            self._log_fail(f"Test 7: {str(e)}")

    async def test_base64_encoding(self):
        """Test 8: Base64 encoding for file content"""
        try:
            import base64

            content = """def hello_world():
    print("Hello, World!")

if __name__ == "__main__":
    hello_world()
"""

            encoded = base64.b64encode(content.encode()).decode()
            decoded = base64.b64decode(encoded).decode()

            assert decoded == content
            assert len(encoded) > len(content)

            self._log_pass("Test 8: Base64 encoding/decoding works")

        except Exception as e:
            self._log_fail(f"Test 8: {str(e)}")

    async def test_workflow_orchestration_logic(self):
        """Test 9: Workflow orchestration logic"""
        try:
            # Test the logical steps of workflow
            steps = [
                ("Create branch", "gca/generated-*"),
                ("Create commit", "Commit generated code"),
                ("Create PR", "Submit for review"),
            ]

            assert len(steps) == 3
            assert steps[0][0] == "Create branch"
            assert steps[1][0] == "Create commit"
            assert steps[2][0] == "Create PR"

            self._log_pass("Test 9: Workflow orchestration has correct steps")

        except Exception as e:
            self._log_fail(f"Test 9: {str(e)}")

    async def test_error_handling_structure(self):
        """Test 10: Error handling structure"""
        try:
            service = GitHubIntegration("test_token")

            # Verify error handling is in place
            assert hasattr(service, 'github')
            assert service.api_url is not None
            assert service.headers is not None
            assert service.access_token is not None

            self._log_pass("Test 10: Error handling structure is in place")

        except Exception as e:
            self._log_fail(f"Test 10: {str(e)}")

    async def test_github_workflow_complete_flow(self):
        """Test 11: Complete GitHub workflow flow"""
        try:
            # Test complete workflow structure
            workflow = GitHubWorkflow("test_token")

            assert workflow.github is not None
            assert hasattr(workflow, 'deploy_generated_code')
            assert callable(workflow.deploy_generated_code)

            self._log_pass("Test 11: GitHub workflow has correct structure")

        except Exception as e:
            self._log_fail(f"Test 11: {str(e)}")

    async def test_response_structure(self):
        """Test 12: GitHub response structure expectations"""
        try:
            # Test expected response structures
            user_response = {
                "login": "username",
                "name": "User Name",
                "email": "user@example.com",
                "id": 12345,
                "avatar_url": "https://avatars.githubusercontent.com/u/12345"
            }

            assert "login" in user_response
            assert "id" in user_response
            assert isinstance(user_response["id"], int)

            self._log_pass("Test 12: Response structures are valid")

        except Exception as e:
            self._log_fail(f"Test 12: {str(e)}")

    def _log_pass(self, test_name: str):
        self.passed += 1
        self.tests_result.append(f"✅ {test_name}")
        print(f"✅ {test_name}")

    def _log_fail(self, test_name: str):
        self.failed += 1
        self.tests_result.append(f"❌ {test_name}")
        print(f"❌ {test_name}")

    async def run_all_tests(self):
        print("\n╔════════════════════════════════════════════════════════════════╗")
        print("║        INTEGRATION TEST - FASE 7 GITHUB INTEGRATION            ║")
        print("║    GitHub API Integration, Workflow Orchestration             ║")
        print("╚════════════════════════════════════════════════════════════════╝\n")

        await self.test_github_service_init()
        await self.test_github_workflow_init()
        await self.test_headers_construction()
        await self.test_branch_name_generation()
        await self.test_commit_message_construction()
        await self.test_pr_body_construction()
        await self.test_api_url_construction()
        await self.test_base64_encoding()
        await self.test_workflow_orchestration_logic()
        await self.test_error_handling_structure()
        await self.test_github_workflow_complete_flow()
        await self.test_response_structure()

        return self.print_results()

    def print_results(self):
        total = self.passed + self.failed
        percentage = (self.passed / total * 100) if total > 0 else 0

        print("\n" + "="*70)
        print("RESULTADOS DO TESTE - FASE 7 GITHUB INTEGRATION")
        print("="*70)
        print(f"\n✅ Passou: {self.passed}/{total}")
        print(f"❌ Falhou: {self.failed}/{total}")
        print(f"📊 Taxa de sucesso: {percentage:.1f}%\n")

        if self.failed == 0:
            print("🎉 TESTES DE GITHUB INTEGRATION COMPLETOS COM SUCESSO!")
            print("\n✨ FASE 7 APROVADA - GITHUB INTEGRATION READY")
            return True
        else:
            print("⚠️  ALGUNS TESTES FALHARAM")
            return False


async def main():
    tester = GitHubTester()
    success = await tester.run_all_tests()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    asyncio.run(main())
